language: c++

addons:
  apt:
    packages: 
    - lcov
    - doxygen
    - graphviz
    - python3
    - python3-pip

jobs:
  include:
    - name: "Ubuntu Build"
      stage: test
      os: linux
      dist: bionic
      after_success: ./bin/gencov.sh
    - name: "macOS Build"
      stage: test
      os: osx
      osx_image: xcode11
    - name: "Documentation Build and Deploy"
      stage: test
      os: linux
      dist: bionic
      install:
        - pip3 install setuptools
        - pip3 install coverxygen
      script: ./bin/gendocs.sh
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: docs/html
        github_token: $GH_REPO_TOKEN
        on:
          branch: devel

install:
  - ./bin/bootstrap.sh

script:
  - . ~/.bashrc
  - mkdir build
  - pushd build
  - cmake ../
  - make -j2
  - popd
  - ./bin/runtests.sh
