language: c++

addons:
  apt:
    packages: 
    - lcov
    - doxygen
    - python3
    - python3-pip

jobs:
  include:
    - os: linux
      dist: bionic
    - os: osx
      osx_image: xcode11

install:
  - bash bootstrap
  - pip3 install setuptools
  - pip3 install coverxygen

script:
  - . ~/.bashrc
  - mkdir build
  - pushd build
  - cmake ../
  - make
  - echo running unit tests...
  - ./test/unit/frontend/frontend_unit_tests
  - ./test/unit/semantic/semantic_unit_tests
  - ./test/unit/semantic/types/typeinference_unit_tests
  - echo running system tests...
  - popd
  - pushd rtlib
  - ./build.sh
  - popd
  - pushd test/system
  - ./run.sh
  - popd 

after_success:
  - lcov --capture --directory build -output-file coverage.info
  - lcov --remove coverage.info '/usr/include/*' -o coverage.info
  - lcov --remove coverage.info '/usr/lib/*' -o coverage.info
  - lcov --remove coverage.info '*.h' -o coverage.info
  - lcov --remove coverage.info '*.hpp' -o coverage.info
  - lcov --list coverage.info
  - bash <(curl -s https://codecov.io/bash) -f coverage.info -cF codecoverage || echo "Codecov did not collect coverage reports"
  - echo generating doccoverage
  - doxygen
  - python3 -m coverxygen --xml-dir xml/ --src-dir . --output doc-coverage.info --kind class
  - bash <(curl -s https://codecov.io/bash) -f doc-coverage.info -cF doccoverage
